### ISSUE TITLE
ruby ./led.rb error

### ISSUE THREAD

**Issue by kwizfreak** [cryptopunksnotdead/cryptopunks#3]
(base) MBP-de-max:led max$ ruby ./led.rb
Traceback (most recent call last):
	2: from ./led.rb:6:in `<main>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- pixelart (LoadError)
(base) MBP-de-max:led max$

**Comment by kwizfreak** [comment]
with 
**gem install pixelart** 
it's ok ...
